### ISSUE TITLE
python3.5 does not support a 'f profix

### ISSUE THREAD

**Issue by airdge** [PetterS/quickjs#16]
```
Collecting quickjs
  Downloading https://files.pythonhosted.org/packages/4e/9f/.../quickjs-1.7.0.tar.gz (377kB)
    100% |████████████████████████████████| 378kB 57kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-g9t_3oka/quickjs/setup.py", line 20
        CONFIG_VERSION = f'\\"{CONFIG_VERSION}\\"'
                                                 ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-g9t_3oka/quickjs/
```
```
CONFIG_VERSION = f'\\"{CONFIG_VERSION}\\"'
CONFIG_VERSION = '\\"{}\\"'.format(CONFIG_VERSION)


CONFIG_VERSION = '"{}"'.format(CONFIG_VERSION)
```

**Comment by PetterS** [comment]
That's correct: this library only supports Python 3.6+. This should probably be more clearly documented.
